
BASE_URL="http://api.praxyk.com:5000/"
# BASE_URL="http://localhost:4001/"
API_VERSION="v1/"
API_BASE_ROUTE=BASE_URL+API_VERSION

LOGIN_ROUTE=API_BASE_ROUTE+"tokens/"
USERS_ROUTE=API_BASE_ROUTE+"users/"
TRANSACTIONS_ROUTE= API_BASE_ROUTE+'transactions/'
RESULTS_ROUTE = API_BASE_ROUTE+'results/'

